version: '3.2'
services:
  webservice:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./config:/config
      - ./data:/data
      - ./websites:/www/websites
    depends_on:
      - php-cgi
    restart: unless-stopped
    networks:
      - website
  php-cgi:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./websites:/www/websites
    restart: unless-stopped
    networks:
      - website
networks:
  website:
